name: Triggered Workflow
run-name: Triggered workflow
on:
  workflow_dispatch:

jobs:
  triggered_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Print payload message
        run: |
            echo "Message from payload: ${{ github.event.inputs.message }}"
