name: Triggered Workflow

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print payload message
        run: |
            echo "Message from payload: ${{ github.event.client_payload.message }}"
