name: Triggered Workflow

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print payload message
        run: echo "Message from payload: ${{ github.event.client_payload.message }}"
