name: Build1
on:
  push:
    branches:
      - master
    paths: subrepo1/**
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: subrepo1
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - run: ls -laR && cd subrepo1
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN1 }}
        with:
            projectBaseDir: subrepo1/
